import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1320px" },
    },
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        alt: ['Cormorant Garamond', 'Georgia', 'serif'],
        num: ['DM Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
          deep: "hsl(var(--primary-deep))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        gold: {
          50: "#FFF9E6",
          100: "#FFF0BF",
          200: "#FFE699",
          300: "#FFDB66",
          400: "#FFD033",
          500: "#FFD700",
          600: "#C9A84C",
          700: "#A8882A",
          800: "#7A6318",
          900: "#4D3E0F",
        },
        royal: {
          50: "#E8E8F0",
          100: "#C5C5DB",
          200: "#9E9EC2",
          300: "#7777A9",
          400: "#555596",
          500: "#1B1B6B",
          600: "#151557",
          700: "#101044",
          800: "#0A0A2E",
          900: "#050518",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in-right": { from: { opacity: "0", transform: "translateX(-20px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "float-slow": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-16px)" } },
        glow: { "0%, 100%": { boxShadow: "0 0 20px hsl(var(--primary) / 0.3)" }, "50%": { boxShadow: "0 0 60px hsl(var(--primary) / 0.6)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.92)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-in-left": { from: { opacity: "0", transform: "translateX(-30px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "slide-in-right": { from: { opacity: "0", transform: "translateX(30px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        sparkle: { "0%, 100%": { opacity: "0", transform: "scale(0) rotate(0deg)" }, "20%": { opacity: "1", transform: "scale(1) rotate(180deg)" }, "80%": { opacity: "1", transform: "scale(1) rotate(180deg)" } },
        "shimmer-skeleton": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "rotate-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        reveal: { from: { opacity: "0", transform: "scale(0.95) translateY(10px)", filter: "blur(4px)" }, to: { opacity: "1", transform: "scale(1) translateY(0)", filter: "blur(0)" } },
        "bounce-in": { "0%": { opacity: "0", transform: "scale(0.3) translateY(-20px)" }, "50%": { transform: "scale(1.05) translateY(4px)" }, "70%": { transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1) translateY(0)" } },
        "page-enter": { from: { opacity: "0", transform: "translateY(20px) scale(0.98)" }, to: { opacity: "1", transform: "translateY(0) scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s cubic-bezier(0.4, 0, 0.2, 1) both",
        "fade-in-right": "fade-in-right 0.5s cubic-bezier(0.4, 0, 0.2, 1) both",
        shimmer: "shimmer 3s ease-in-out infinite",
        "float-slow": "float-slow 8s ease-in-out infinite",
        glow: "glow 3s ease-in-out infinite",
        "scale-in": "scale-in 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "slide-in-left": "slide-in-left 0.5s cubic-bezier(0.4, 0, 0.2, 1) both",
        "slide-in-right": "slide-in-right 0.5s cubic-bezier(0.4, 0, 0.2, 1) both",
        sparkle: "sparkle 3s ease-in-out infinite",
        "shimmer-skeleton": "shimmer-skeleton 1.8s ease-in-out infinite",
        "rotate-slow": "rotate-slow 20s linear infinite",
        reveal: "reveal 0.7s cubic-bezier(0.4, 0, 0.2, 1) both",
        "bounce-in": "bounce-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both",
        "page-enter": "page-enter 0.6s cubic-bezier(0.4, 0, 0.2, 1) both",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
